SamsSoup/Models/Soup.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace SamsSoup.Models
{
    public class Soup
    {
        public int Id { get; set; }
        [Remote("CheckIfSoupNameAlreadyExists", "SoupManagement", ErrorMessage = "The soup name is already taken")]
        public string SoupName { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        //public string ImageFilePath { get; set; }
        public bool IsSoupOfTheWeek { get; set; }
        public decimal Price { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
        public virtual List<SoupReview> SoupReviews { get; set; }
    }
}

SamsSoup/Controllers/SoupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.NetworkInformation;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SamsSoup.Data.Interfaces;
using SamsSoup.Models;
using SamsSoup.ViewModels;

namespace SamsSoup.Controllers
{
    public class SoupController : Controller
    {
        private readonly ISoupRepository _soupRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly ISoupReviewRepository _soupReviewRepository;
        private readonly HtmlEncoder _htmlEncoder;

        public SoupController(ISoupRepository soupRepository, ICategoryRepository categoryRepository, ISoupReviewRepository soupReviewRepository, HtmlEncoder htmlEncoder)
        {
            _soupRepository = soupRepository;
            _categoryRepository = categoryRepository;
            _soupReviewRepository = soupReviewRepository;
            _htmlEncoder = htmlEncoder;
        }

        public ViewResult List(string category)
        {
            IEnumerable<Soup> soups;
            string currentCategory;

            if (string.IsNullOrEmpty(category))
            {
                soups = _soupRepository.AllSoups.OrderBy(s => s.Id);
                currentCategory = "All Soups";
            }
            else
            {
                soups = _soupRepository.AllSoups.Where(p => p.Category.CategoryName == category).OrderBy(s => s.Id);
                currentCategory = _categoryRepository.AllCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }

            return View(new SoupsListViewModel
            {
                Soups = soups,
                CurrentCategory = currentCategory
            }); 
        }

        public IActionResult Details(int id)
        {
            var soup = _soupRepository.GetSoupById(id);
            if (soup == null) return NotFound();
            var reviews = _soupReviewRepository.GetSoupReviewsForPie(id);
            return View(new SoupDetailViewModel() { Soup = soup, Reviews = reviews });
        }

        [HttpPost]
        public IActionResult Details(int id, string review)
        {
            var soup = _soupRepository.GetSoupById(id);
            if (soup == null) return NotFound();
            var reviews = _soupReviewRepository.GetSoupReviewsForPie(id);

            string encodedReview = _htmlEncoder.Encode(review);
            _soupReviewRepository.AddSoupReview(new SoupReview() { Soup = soup, Review = encodedReview });

            return View(new SoupDetailViewModel() { Soup = soup, Reviews = reviews });
        }
    }
}

SamsSoup/Views/Soup/Details.cshtml
@using System.Net
@using System.Threading.Tasks
@model SoupDetailViewModel

<h2>@Model.Soup.SoupName</h2>
<div>
    <h3>@Model.Soup.ShortDescription</h3>
    <p>@Model.Soup.LongDescription</p>
    <div class="p2">
        <p class="btn">
            <a class="btn btn-success"
               asp-controller="ShoppingCart"
               asp-action="AddToShoppingCart"
               asp-route-soupId="@Model.Soup.Id">Add To Cart</a>
        </p>
    </div>
</div>

<h3>Reviews for this soup</h3>

@foreach (var review in @Model.Reviews)
{
     <div>@System.Net.WebUtility.HtmlDecode(review.Review)</div>
 
}

<form asp-action="Details" asp-controller="Soup" role="form" method="post">
    <h4>Write a review</h4>
    <hr />
    <input type="hidden" asp-for="@Model.Soup.Id" />
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Review"></label>
        <input asp-for="Review" class="form-control" />
        <span asp-validation-for="Review" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" class="btn btn-success" value="Post Review" />
    </div>
</form>

SamsSoup/Views/Soup/List.cshtml
@model SoupsListViewModel

    <h1>@Model.CurrentCategory</h1>
    @foreach (var soup in Model.Soups)
    {
        <partial name="_SoupCard" model="soup"/>
    }