SamsSoup/Controllers/SoupGiftController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SamsSoup.Data.Interfaces;
using SamsSoup.Models;

namespace SamsSoup.Controllers
{
    public class SoupGiftController : Controller
    {
        private readonly ISoupRepository _soupRepository;
        private readonly IOrderRepository _orderRepository;

        public SoupGiftController(ISoupRepository soupRepository, IOrderRepository orderRepository)
        {
            _soupRepository = soupRepository;
            _orderRepository = orderRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public IActionResult Index(SoupGiftOrder soupGiftOrder)
        {
            var soupOfTheWeek = _soupRepository.SoupsOfTheWeek.FirstOrDefault();
            if(soupOfTheWeek != null)
            {
                soupGiftOrder.Soup = soupOfTheWeek;
                _orderRepository.CreateSoupGiftOrder(soupGiftOrder);
                return RedirectToAction("SoupGiftOrderComplete");
            }
            return View();
        }

        public IActionResult SoupGiftOrderComplete()
        {
            ViewBag.SoupGiftOrderCompleteMessage = HttpContext.User.Identity.Name + ", thanks for ordering";
            return View();
        }
    }
}

SamsSoup/Views/SoupGift/Index.cshtml
@model SoupGiftOrder

<h2>Give a soup</h2>

<form asp-action="Index" asp-controller="SoupGift" method="post">
    <h4>Enter the details</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" class="btn btn-primary" value="Send Soup"/>
    </div>
</form>

SamsSoup/Views/SoupGift/SoupGiftOrderComplete.cshtml
<h1>@ViewBag.SoupGiftOrderCompleteMessage </h1>