SamsSoup/Controllers/SoupManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using SamsSoup.Data.Interfaces;
using SamsSoup.Models;
using SamsSoup.ViewModels;

namespace SamsSoup.Controllers
{

    public class SoupManagementController : Controller
    {
        private readonly ISoupRepository _soupRepository;
        private readonly ICategoryRepository _categoryRepository;

        public SoupManagementController(ISoupRepository soupRepository, ICategoryRepository categoryRepository)
        {
            _soupRepository = soupRepository;
            _categoryRepository = categoryRepository;
        }
        public ViewResult Index()
        {
            var soups = _soupRepository.AllSoups.OrderBy(p => p.Id);
            return View(soups);
        }

        public IActionResult AddSoup()
        {
            var categories = _categoryRepository.AllCategories;
            var soupEditViewModel = new SoupEditViewModel
            {
                Categories = categories.Select(c => new SelectListItem() { Text = c.CategoryName, Value = c.Id.ToString() }).ToList(),
                CategoryId = categories.FirstOrDefault().Id
            };
            return View(soupEditViewModel);
        }
        [HttpPost]
        public IActionResult AddSoup([Bind("Soup")]SoupEditViewModel soupEditViewModel)
        {
            //Custom Validation
            if(ModelState.GetValidationState("Soup.Price") == ModelValidationState.Valid
                && soupEditViewModel.Soup.Price < 0)
            {
                ModelState.AddModelError(nameof(soupEditViewModel.Soup.Price), "The price of the soup must be higher than zero");
            }
            //Basic validation
            if (ModelState.IsValid)
            {
                _soupRepository.CreateSoup(soupEditViewModel.Soup);
                return RedirectToAction("Index");
            }
            return View(soupEditViewModel);
        }
        public IActionResult EditSoup(int soupId)
        {
            var categories = _categoryRepository.AllCategories;

            var soup = _soupRepository.AllSoups.FirstOrDefault(p => p.Id == soupId);

            var soupEditViewModel = new SoupEditViewModel
            {
                Categories = categories.Select(c => new SelectListItem() { Text = c.CategoryName, Value = c.Id.ToString() }).ToList(),
                Soup = soup,
                CategoryId = soup.CategoryId
            };

            var item = soupEditViewModel.Categories.FirstOrDefault(c => c.Value == soup.CategoryId.ToString());
            item.Selected = true;

            return View(soupEditViewModel);
        }
        [HttpPost]
        public IActionResult EditSoup(SoupEditViewModel soupEditViewModel)
        {
            soupEditViewModel.Soup.CategoryId = soupEditViewModel.CategoryId;

            if (ModelState.IsValid)
            {
                _soupRepository.UpdateSoup(soupEditViewModel.Soup);
                return RedirectToAction("Index");
            }
            return View(soupEditViewModel);
        }

        [HttpPost]
        public IActionResult DeleteSoup(int soupId)
        {
            var categories = _categoryRepository.AllCategories;

            var soup = _soupRepository.AllSoups.FirstOrDefault(s => s.Id == soupId);
            _soupRepository.DeleteSoup(soup);
            return RedirectToAction("Index");
        }
        public IActionResult QuickEdit()
        {
            var soupNames = _soupRepository.AllSoups.Select(s => s.SoupName).ToList();
            return View(soupNames);
        }

        [HttpPost]
        public IActionResult QuickEdit(List<string> soups)
        {
            var models = _soupRepository.AllSoups.ToList();

            for (var i = 0; i < models.Count; i++)
            {
                models[i].SoupName = soups[i];
            }

            _soupRepository.UpdateMultipleSoups(models);
            return View(soups);
        }
        public IActionResult BulkEditSoups()
        {
            var soups = _soupRepository.AllSoups.ToList();
            return View(soups);
        }

        [HttpPost]
        public IActionResult BulkEditSoups(List<Soup> soups)
        {
            var models = _soupRepository.AllSoups.ToList();
            for(var i = 0; i < models.Count; i++)
            {
                models[i].SoupName = soups[i].SoupName;
                models[i].Price = soups[i].Price;
                models[i].ShortDescription = soups[i].ShortDescription;
            }
            _soupRepository.UpdateMultipleSoups(models);
            return View(models);
        }

        [AcceptVerbs("Get", "Post")]
        public IActionResult CheckIfSoupNameAlreadyExists([Bind(Prefix = "Soup.SoupName")]string soupName)
        {
            var soup = _soupRepository.AllSoups.FirstOrDefault(s => s.SoupName == soupName);
            return soup == null ? Json(true) : Json("The soup name is already taken");
        }

    }
}

SamsSoup/Views/SoupManagement/AddSoup.cshtml
@model SoupEditViewModel

<h2>Create a new Soup</h2>

<form asp-controller="SoupManagement" asp-action="AddSoup" method="post" role="form">
    <h4>Enter the Soup details below</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Soup.SoupName" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Soup.SoupName" class="form-control" />
            <span asp-validation-for="Soup.SoupName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Soup.ShortDescription" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Soup.ShortDescription" class="form-control" />
            <span asp-validation-for="Soup.ShortDescription" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Soup.LongDescription" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Soup.LongDescription" class="form-control" />
            <span asp-validation-for="Soup.LongDescription" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Soup.Price" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Soup.Price" class="form-control" />
            <span asp-validation-for="Soup.Price" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Soup.IsSoupOfTheWeek" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Soup.IsSoupOfTheWeek" class="form-control" />
            <span asp-validation-for="Soup.IsSoupOfTheWeek" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Categories" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <select asp-for="Soup.CategoryId" class="form-control"
                    asp-items="Model.Categories"></select>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="Create Soup" />
        </div>
    </div>
</form>

SamsSoup/Views/SoupManagement/BulkEditSoups.cshtml
@model List<Soup>

<form asp-action="BulkEditSoups" method="post">
    @for (var i = 0; i < Model.Count; i++)
    {
        <div class="form-group">
            <label asp-for="@Model[i].SoupName"></label>
            <input asp-for="@Model[i].SoupName" class="form-control" />
            <span asp-validation-for="@Model[i].SoupName"></span>
        </div>

        <div class="form-group">
            <label asp-for="@Model[i].Price"></label>
            <input asp-for="@Model[i].Price" class="form-control" />
            <span asp-validation-for="@Model[i].Price"></span>
        </div>

        <div class="form-group">
            <label asp-for="@Model[i].ShortDescription"></label>
            <input asp-for="@Model[i].ShortDescription" class="form-control" />
            <span asp-validation-for="@Model[i].ShortDescription"></span>
        </div>
    }
    <button type="submit" class="btn btn-primary">Save</button>
</form>

SamsSoup/Views/SoupManagement/DeleteSoup.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

SamsSoup/Views/SoupManagement/EditSoup.cshtml
@model SoupEditViewModel

<h2>Edit Soup</h2>

<form asp-controller="SoupManagement" asp-action="EditSoup" method="post" class="form-horizontal" role="form">
    <h4>Update the Soup details below</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Soup.Id" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Soup.Id" class="form-control" readonly="readonly"/>
            <span asp-validation-for="Soup.Id" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Soup.SoupName" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Soup.SoupName" class="form-control" />
            <span asp-validation-for="Soup.SoupName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Soup.ShortDescription" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Soup.ShortDescription" class="form-control" />
            <span asp-validation-for="Soup.ShortDescription" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Soup.LongDescription" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Soup.LongDescription" class="form-control" />
            <span asp-validation-for="Soup.LongDescription" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Soup.Price" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Soup.Price" class="form-control" />
            <span asp-validation-for="Soup.Price" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Soup.IsSoupOfTheWeek" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Soup.IsSoupOfTheWeek" class="form-control" />
            <span asp-validation-for="Soup.IsSoupOfTheWeek" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Categories" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <select asp-for="CategoryId" class="form-control"
                    asp-items="Model.Categories"></select>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="Update Soup" />
        </div>
    </div>
</form>

SamsSoup/Views/SoupManagement/Index.cshtml
@model IEnumerable<Soup>

<h2>Soup Management</h2>

@if (!Model.Any())
{
    <tr><td colspan="3" class="text-center">No Soups at this point :()</td></tr>
}
else
{
    <table class="table">
        <tr>
            <th>Soup ID</th>
            <th>Name</th>
            <th>Price</th>
            <th>Actions</th>
        </tr>
        @foreach (var Soup in Model)
        {
            <tr>
                <td>@Soup.Id</td>
                <td>@Soup.SoupName</td>
                <td>@Soup.Price</td>
                <td>
                    <form asp-action="DeleteSoup" asp-route-soupId="@Soup.Id" method="post">
                        <a class="btn btn-sm btn-primary" asp-action="EditSoup" asp-route-soupId="@Soup.Id">Edit</a>
                        <button type="submit" onclick="return confirm('Do you really want to delete this Soup?');" class="btn btn-sm btn-danger">
                            Delete
                        </button>
                    </form>
                </td>
            </tr>
        }
    </table>
}
<p>
    <a class="btn btn-primary" asp-action="AddSoup">Add new Soup</a>
    <a class="btn btn-primary" asp-action="QuickEdit">Edit Soup Names</a>
    <a class="btn btn-primary" asp-action="BulkEditSoups">Edit Soups in Bulk</a>
</p>

SamsSoup/Views/SoupManagement/QuickEdit.cshtml
@model IList<string>

@if (Model.Count > 0)
{
    <form asp-action="QuickEdit" method="post">
        @for (var i = 0; i < Model.Count; i++)
        {
        <div class="form-group">
            <label>Soup name @(i + 1)</label>
            <input asp-for="@Model[i]" name="soups" id="soups" class="form-control"/>
        </div>
        }
        <samsbutton content="Update" button-style="primary"/>
    </form>
}
else
{
    <h2>No Soups in the system</h2>
}